### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Megh2005**
I have modified and decorated the readme file. Now it's looking like this

https://github.com/user-attachments/assets/b53109ef-c1f0-42c0-9eb4-4f9d3cf9c247

### CODE REVIEW

**Comment by mrpankajpandey** [comment]
Nice work! @Megh2005 ,I will review and merge it @Megh2005

**Comment by Megh2005** [comment]
Sure @mrpankajpandey I am checking this
Trying to rebuild that

**Comment by mrpankajpandey** [comment]
And also try to create new branch for each issue.
Don't push main to main.

**Comment by Megh2005** [comment]
> And also try to create new branch for each issue. Don't push main to main.

As these are non coding issues, it can't have any merge conflicts. That's why I was just pushing it to the main branch 

I can push it to the seperate branch also. Not a big deal

**Pull request merged**
